package com.example.uma.ui.screens.models

data class DetailedCharacterInfo(
    val basicCharacterInfo: BasicCharacterInfo,
    val birthDay: Int?,
    val birthMonth: Int?,
    val categoryLabel: String,
    val categoryLabelEn: String,
    val categoryValue: String,
    val colorMain: String,
    val colorSub: String,
    val detailImgPc: String?,
    val detailImgSp: String?,
    val earsFact: String?,
    val familyFact: String?,
    val gameId: Int?,
    val grade: String?,
    val height: Int?,
    val id: Int,
    val link: String,
    val nameEn: String,
    val nameEnInternal: String,
    val nameJp: String,
    val preferredUrl: String,
    val profile: String?,
    val residence: String?,
    val rowNumber: Int,
    val shoeSize: String?,
    val sizeB: Int?,
    val sizeH: Int?,
    val sizeW: Int?,
    val slogan: String?,
    val snsHeader: String,
    val snsIcon: String,
    val strengths: String?,
    val tailFact: String?,
    val thumbImg: String,
    val voice: String?,
    val weaknesses: String?,
    val weight: String?
)


